Added fetch proxy
Groopit/ra-data-odata-server pull request #13
Opened 2022-11-03 22:29 UTC by gebsl

Hi John,

here is my first proposal for the fetch proxy implementation. It still needs some documentation (metadata-request needs to return a string, whereas all other (content) requests need to be returned as json) and possibly some test cases.

I avoided the type hell by just shifting the responsibility to the user of the library. He/she needs to deal with types around the custom fetch implementation, so the library should not be affected by any type issues. Basically I just re-used what @odata/client exposes as `ODataNewOptions`. This way the user is free to configure everything that's provided by @odata/client.

Any thoughts, criticism, improvements appreciated!

2022-11-09 19:17 UTC, jvert requested changes

2022-11-09 19:17 UTC, jvert commented on src/index.ts
> +    const m = await fetch(url);
we should still pass the commonHeaders to fetch() here, otherwise token-based authentication won't work unless you implement a fetchProxy for it.

2022-11-10 14:22 UTC, gebsl commented on src/index.ts
> +    const m = await fetch(url);
Sounds reasonable. I pushed a commit, adding the headers to this fetch call. Also, I updated the test case to also check if the fetch proxy is working properly.

What's left from my side is documentation in README.md. Do you prefer updating the documentation or should I include the new features including example usage?

2022-11-10 16:27 UTC, jvert approved these changes

2022-11-10 16:28 UTC, jvert commented on src/index.ts
> +    const m = await fetch(url);
I have a doc update - I'll add it after this is merged when I do the release. Thanks for the contribution!

2022-11-10 16:28 UTC, merged